_BASE_: ../base-linear.yaml
OUTPUT_DIR: outputs/peft_transformer/linear
DATA:
  NAME: OxfordFlowers
  DATAPATH: /path/to/flowers-102
  FEATURE: sup_vitb16_224
  NUMBER_CLASSES: 102
  BATCH_SIZE: 64
  NUM_WORKERS: 4
MODEL:
  TYPE: vit
  TRANSFER_TYPE: linear
SOLVER:
  TOTAL_EPOCH: 50
  BASE_LR: 1.0e-3
  WEIGHT_DECAY: 1.0e-4
  LOG_EVERY_N: 10
